/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ParticipationRequest } from '../model/models';
import { ParticipationResponse } from '../model/models';
import { UpdateSurvey400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddParticipationRequestParams {
    participationRequest: ParticipationRequest;
}

export interface DeleteBrandRequestParams {
    id: number;
}

export interface GetParticipationByIdRequestParams {
    id: number;
}

export interface UpdateParticipationRequestParams {
    participationRequest: ParticipationRequest;
}


export interface ParticipationControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addParticipation(requestParameters: AddParticipationRequestParams, extraHttpRequestParams?: any): Observable<ParticipationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteBrand(requestParameters: DeleteBrandRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllParticipation(extraHttpRequestParams?: any): Observable<Array<ParticipationResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getParticipationById(requestParameters: GetParticipationByIdRequestParams, extraHttpRequestParams?: any): Observable<ParticipationResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateParticipation(requestParameters: UpdateParticipationRequestParams, extraHttpRequestParams?: any): Observable<ParticipationResponse>;

}
