/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { QuestionRequest } from '../model/models';
import { QuestionResponse } from '../model/models';
import { UpdateSurvey400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AddQuestionRequestParams {
    questionRequest: QuestionRequest;
}

export interface DeleteQuestionRequestParams {
    id: number;
}

export interface GetQuestionByIdRequestParams {
    id: number;
}

export interface UpdateQuestionRequestParams {
    questionRequest: QuestionRequest;
}


export interface QuestionControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    addQuestion(requestParameters: AddQuestionRequestParams, extraHttpRequestParams?: any): Observable<QuestionResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteQuestion(requestParameters: DeleteQuestionRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllQuestion(extraHttpRequestParams?: any): Observable<Array<QuestionResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getQuestionById(requestParameters: GetQuestionByIdRequestParams, extraHttpRequestParams?: any): Observable<QuestionResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateQuestion(requestParameters: UpdateQuestionRequestParams, extraHttpRequestParams?: any): Observable<QuestionResponse>;

}
