/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Survey } from '../model/models';
import { SurveyRequest } from '../model/models';
import { SurveyResponse } from '../model/models';
import { UpdateSurvey400Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateSurveyRequestParams {
    surveyRequest: SurveyRequest;
}

export interface DeleteSurveyRequestParams {
    id: number;
}

export interface GetSurveyByIdRequestParams {
    id: number;
}

export interface UpdateSurveyRequestParams {
    surveyRequest: SurveyRequest;
}


export interface SurveyControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createSurvey(requestParameters: CreateSurveyRequestParams, extraHttpRequestParams?: any): Observable<Survey>;

    /**
     * 
     * 
* @param requestParameters
     */
    deleteSurvey(requestParameters: DeleteSurveyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
*/
    getAllSurvey(extraHttpRequestParams?: any): Observable<Array<SurveyResponse>>;

    /**
     * 
     * 
* @param requestParameters
     */
    getSurveyById(requestParameters: GetSurveyByIdRequestParams, extraHttpRequestParams?: any): Observable<SurveyResponse>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateSurvey(requestParameters: UpdateSurveyRequestParams, extraHttpRequestParams?: any): Observable<SurveyResponse>;

}
