/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GrantedAuthority } from './granted-authority';


export interface User { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    password?: string;
    city?: string;
    role?: User.RoleEnum;
    enabled?: boolean;
    accountNonLocked?: boolean;
    authorities?: Array<GrantedAuthority>;
    username?: string;
    accountNonExpired?: boolean;
    credentialsNonExpired?: boolean;
}
export namespace User {
    export type RoleEnum = 'USER' | 'ADMIN';
    export const RoleEnum = {
        User: 'USER' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum
    };
}


